name: cubit_weather
description: "It's about weather and use Flutter cubit structure"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #State Management
  flutter_bloc: ^8.1.6

  #Font
  google_fonts: ^6.2.1

  #Network
  http: ^1.2.1

  #Model parse
  json_annotation: ^4.9.0


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  bloc_test: ^9.1.7
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

